### ISSUE TITLE
Return _unicodeSequenceMarker when list is null or empty

### ISSUE THREAD

**Issue by Konard** [linksplatform/Data.Doublets.Sequences#20]
Here we should check for IsNullOrEmpty for the list:
https://github.com/linksplatform/Data.Doublets.Sequences/blob/246bcf67432762235dc8550eabd8b5cd2ae280e5/csharp/Platform.Data.Doublets.Sequences/Unicode/UnicodeSymbolsListToUnicodeSequenceConverter.cs#L93-L95

_unicodeSequenceMarker as a sequence should mean empty sequence.

And, here if we receive _unicodeSequenceMarker (it should be added to the constructor too) we should return empty string:
https://github.com/linksplatform/Data.Doublets.Sequences/blob/246bcf67432762235dc8550eabd8b5cd2ae280e5/csharp/Platform.Data.Doublets.Sequences/Unicode/UnicodeSequenceToStringConverter.cs#L77-L81

We also can make constructor with only _unicodeSequenceMarker, it should use it to create Unicode sequence criterion matcher.

**Comment by Konard** [comment]
Do you have few options?

**Comment by FreePhoenix888** [comment]
> Do you have few options?

Where the `Unicode sequence matcher based on TargetMatcher must be located? How must it be called? Is there any example how custom matcher should look? I see only `TargetMatcher` in `CretirionMatchers`

**Comment by Konard** [comment]
It should be located in this repository in [CriterionMatchers](https://github.com/linksplatform/Data.Doublets.Sequences/tree/main/csharp/Platform.Data.Doublets.Sequences/CriterionMatchers) folder.

Do you have any ideas on how to name it? Options to choose from?

**Comment by FreePhoenix888** [comment]
> It should be located in this repository in [CriterionMatchers](https://github.com/linksplatform/Data.Doublets.Sequences/tree/main/csharp/Platform.Data.Doublets.Sequences/CriterionMatchers) folder.
> 
> Do you have any ideas on how to name it? Are there options to choose from?

`UnicodeSequenceTargetMatcher`?

**Comment by Konard** [comment]
UnicodeSequenceMatcher. Whether target or source are checked is an implementation detail and can be changed in the future without changing the name of the class.
